config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :lists do
    resources :items, only: [:create, :update, :destroy]
  end

  delete '/lists/:list_id/clear_complete_items' => 'items#clear_complete_items', as: 'clear_complete_items'

  root to: 'welcome#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
  after_create :set_to_incomplete

  validates :name, presence: true

  def days_left
    7 - (DateTime.now.to_date - created_at.to_date).to_i
  end

  def complete?
    self.completed
  end

  private

  def set_to_incomplete
    self.update(completed: false)
  end
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :items, dependent: :destroy

  validates :name, presence: true

  default_scope { order(:name) }

  def complete_items
    items.where('completed = ?', true)
  end

  def incomplete_items
    items.where('completed = ?', false)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :lists, dependent: :destroy

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name << :last_name
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @item = @list.items.build(item_params)
    if @list.save
      respond_to do |format|
        format.html { redirect_to list }
        format.js
      end
    end
  end

  def update
    @list = List.find(params[:list_id])
    @item = Item.find(params[:id])
    @item.update_attributes(completed: true)
    respond_to do |format|
      format.html { redirect_to @list }
      format.js
    end
  end

  def destroy
    @list = List.find(params[:list_id])
    @item = Item.find(params[:id])
    @item.destroy
    respond_to do |format|
      format.html { redirect_to @list }
      format.js
    end
  end

  def clear_complete_items
    @list = List.find(params[:list_id])
    @list.complete_items.each do |item|
      item.destroy
    end

    respond_to do |format|
      format.html { redirect_to @list }
      format.js
    end
  end

  private

  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @lists = current_user.lists.page(params[:page]).per(10)
  end

  def show
    @list = List.find(params[:id])
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user
    if @list.save
      respond_to do |format|
        format.html do
          flash[:notice] = 'A new list has been successfully added.'
          redirect_to lists_path
        end
        format.js
      end
    else
      flash[:error] = 'Error while adding a new list.'
      render :index
    end
  end

  def update
    list = List.find(params[:id])
    list.update(list_params)
    redirect_to lists_path
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    respond_to do |format|
      format.js
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message
            end)
    end
    nil
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/items/_form.html.erb
<%= form_for [list, Item.new], remote: true do |f| %>
  <div class="input-group">
    <%= f.text_field :name, class: 'form-control', placeholder: 'Enter Item' %>
    <span class="input-group-btn">
      <%= f.submit 'New Item', class: 'btn btn-default' %>
    </span>
  </div>
<% end %>

app/views/items/_item.html.erb
<li class="list-group-item" id="item-<%= item.id %>">
  <% if !item.complete? %>
    <%= link_to '', [@list, item], method: :patch, remote: true,
      class: 'item glyphicon glyphicon-unchecked' %>
  <% else %>
     <span class="glyphicon glyphicon-check"></span>
  <% end %>
  <span class="item"><%= item.name %></span>
  <% if !item.complete? %>
    <span class="badge"><%= pluralize(item.days_left, 'day') %> left</span>
  <% else %>
    <div class="pull-right">
      <%= link_to '', [@list, item], method: :delete, remote: true,
        class: 'btn btn-danger btn-xs glyphicon glyphicon-remove' %>
    </div>
  <% end %>
</li>

app/views/items/clear_complete_items.js.erb
$('#complete-tasks').empty();

app/views/items/create.js.erb
$('#items').prepend('<%= j render partial: 'items/item', locals: { list: @list, item: @item } %>');
$('#incomplete-item-count').html('<%= @list.incomplete_items.count %>');

$('#new_item').html("<%= j render partial: 'items/form', locals: { list: @list } %>")

app/views/items/destroy.js.erb
$('#item-' + <%= @item.id %>).fadeOut();

app/views/items/update.js.erb
<% if @item.complete? %>
  $('#item-' + <%= @item.id %>).remove();
  $('#complete-tasks').prepend('<%= j render partial: 'item', locals: { list: @list, item: @item } %>')
<% else %>
  $('#incomplete-tasks').prepend('<%= j render partial: 'item', locals: { list: @list, item: @item } %>')
<% end %>
$('#incomplete-item-count').html('<%= @item.list.incomplete_items.count %>');

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <%= link_to 'Blocitoff', root_path, class: 'navbar-brand' %>

    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li><%= link_to 'My TODO', lists_path %></li>
        <li><%= link_to current_user.full_name, edit_user_registration_path(current_user) %></li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-lg' do %>
            <span class="glyphicon glyphicon-log-out"></span>
          <% end %>
        </li>
      <% else %>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='container'>

<%= render 'layouts/header' %>
<%= flash_messages %>
<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<div class="row">
  <%= form_for List.new, remote: true do |f| %>
    <div class="input-group">
      <%= f.text_field :name, class: 'form-control' %>
      <span class="input-group-btn">
        <%= f.submit 'New List', class: 'btn btn-default' %>
      </span>
    </div>
  <% end %>
</div>

app/views/lists/_list.html.erb
<%= content_tag :div, id: "list-#{list.id}" do %>
  <li class="list-group-item">
    <h5 class="list-group-item-heading"><%= link_to list.name, list %></h5>
    <small><%= pluralize(list.items.count, 'item') %> remaining</small>
    <div class="pull-right">
      <%= link_to list, method: :delete, class: 'btn btn-danger btn-xs', remote: true,
        data: { confirm: 'Delete list will also delete its associated items. Are you sure?' } do %>
        <span class="glyphicon glyphicon-trash"></span>
      <% end %>
    </div>
  </li>
<% end %>

app/views/lists/create.js.erb
$('.list-group').prepend('<%= j render(partial: @list, locals: { list: @list }) %>');

$('#new_list').html('<%= j render 'form' %>');

app/views/lists/destroy.js.erb
$('#list-' + <%= @list.id %>).hide();

app/views/lists/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-offset-4 col-sm-4">
      <div class="row">
        <h3 class="text-center">My List</h3>
      </div>

      <%= render 'form' %>

        <ul class="list-group">
          <%= render @lists %>
        </ul>
        <div class="text-center">
          <%= paginate @lists %>
        </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-offset-3 col-sm-6">
      <h3 class="text-center"><%= @list.name %>
      <span class="badge" id="incomplete-item-count"><%= @list.incomplete_items.count %></span></h3>
      <%= render partial: 'items/form', locals: { list: @list } %>
      <ul class="list-group" id="items">
        <%= render @list.incomplete_items %>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-offset-3 col-sm-6">
      <div class="panel panel-default">
        <div class="panel-heading"><b>Complete Items</b>
          <div class="pull-right">
            <%= link_to 'Remove All', clear_complete_items_path(@list), method: :delete, class: 'btn btn-danger btn-xs',
              remote: true, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
          <ul class="list-group" id="complete-tasks">
            <%= render @list.complete_items %>
          </ul>
      </div>
    </div>
  </div>

</div>

app/views/welcome/index.html.erb
<h1>Welcome to Blocitoff</h1>

<p>You can manage your to-do list with ease.</p>